name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/setup-uv@v6
    - uses: actions/setup-python@v4
      with:
        python-version-file: .python-version
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Run tests
      run: uv run pytest