name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: pipenv install
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install

    - name: Run tests
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run tests
