name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: pipenv install
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install

    - name: Run tests w/ coverage
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run test_coverage

    - name: Generate coverage report
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run coverage lcov

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        coverageLocations: |
          ${{github.workspace}}/coverage.lcov:lcov